server:
  servlet:
    context-path: /api

spring:
  application.name: comprandoencasa
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DATASOURCE_HEROKU_USERNAME}
    password: ${DATASOURCE_HEROKU_PASSWORD}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update

google.api.key: ${GOOGLE_API_KEY}

auth0:
  domain: ${AUTH0_DOMAIN}
  clientId: ${AUTH0_CLIENT_ID}
security:
  oauth2:
    resource:
      id: ${OAUTH2_RESOURCE_ID}
      jwk.keySetUri: ${OAUTH2_JWT_URI}