spring:
  application.name: comprandoencasa
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: sa
    password: ${DATASOURCE_HEROKU_PASSWORD}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update

google.api.key: ${GOOGLE_API_KEY}