spring:
  application.name: comprandoencasa
#  datasource:
#    url: ${DATASOURCE_URL}
#    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME}
#    username: ${DATASOURCE_USER_NAME}
#    password: ${DATASOURCE_PASSWORD}
#  jpa.database-platform: ${JPA_DATABASE_PLATFORM}


google.api.key: ${GOOGLE_API_KEY}
